[package]
name = "template-icd"
version = "0.1.0"
edition = "2021"

[dependencies.serde]
version = "1.0"
features = ["derive"]
default-features = false

[dependencies.postcard-rpc]
version = "0.10"

[dependencies.postcard-schema]
version = "0.1"
features = ["derive"]

[features]
use-std = []
